// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#include "../fattn-tile.cuh"

DECL_FATTN_TILE_CASE(256, 256);

// Not autogenerated: the native quantized-KV tile instance, see
// ggml_cuda_fattn_tile_use_native_kv in fattn-tile.cuh.
DECL_FATTN_TILE_CASE_KV(256, 256, GGML_TYPE_Q4_0, GGML_TYPE_Q4_0);
